name: Montana

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get -y install docker-compose

      - name: Build and run containers
        run: |
          docker-compose up -d --build
          docker-compose exec laravel.test php artisan key:generate
          docker-compose exec laravel.test php artisan migrate --seed
          docker-compose exec laravel.test php artisan passport:install

      - name: Run tests
        run: docker-compose exec app php artisan test

      - name: Shut down containers
        run: docker-compose down
