name: Montana

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: montana
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: |
          cp .env.ci .env
          composer install --no-interaction

      - name: Prepare Laravel Application
        run: |
          php artisan key:generate
          php artisan migrate
          php artisan passport:install
          php artisan db:seed

      - name: Start Laravel app
        run: |
          php artisan serve --port=80 &
          sleep 10 # Give the server some time to start

      - name: Run tests
        run: php artisan test

      - name: Stop Laravel app
        run: |
          pkill -f "php artisan serve"
